# Site settings
title: Taeng's Blog
description: '공부를 위한 개인 기록용 블로그입니다. 실제 포스팅은 다른 곳에서 이루어지고 있습니다.'
url: 'http://ytw0415.github.io/'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'Josh Gerdes'
  email: josh@joshgerdes.com
  twitter_username: 
  facebook_username: 
  github_username:  
  linkedin_username:  

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
